[workspace]

members = ["localsend-lib-messages"]

[workspace.dependencies]
derive_more = "1"
mediatype = "0.19"
serde = "1.0"
serde-bool = "0.1.3"
serde_json = "1.0"
serde_with = "3.11.0"
thiserror = "1.0.64"
typed-builder = "0.20.0"
